/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface AddRolePermissionsRequestContent {
    /** array of resource_server_identifier, permission_name pairs. */
    permissions: Management.PermissionRequestPayload[];
}
