/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssignOrganizationMemberRolesRequestContent {
    /** List of roles IDs to associated with the user. */
    roles: string[];
}
