/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssignRoleUsersRequestContent {
    /** user_id's of the users to assign the role to. */
    users: string[];
}
