/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssociateOrganizationClientGrantRequestContent {
    /** A Client Grant ID to add to the organization. */
    grant_id: string;
}
