/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateRoleRequestContent {
    /** Name of the role. */
    name: string;
    /** Description of the role. */
    description?: string;
}
