/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface CreatePublicKeyDeviceCredentialRequestContent {
    /** Name for this device easily recognized by owner. */
    device_name: string;
    type: Management.DeviceCredentialPublicKeyTypeEnum;
    /** Base64 encoded string containing the credential. */
    value: string;
    /** Unique identifier for the device. Recommend using <a href="http://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID">Android_ID</a> on Android and <a href="https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIDevice_Class/index.html#//apple_ref/occ/instp/UIDevice/identifierForVendor">identifierForVendor</a>. */
    device_id: string;
    /** client_id of the client (application) this credential is for. */
    client_id?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
