/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateOrganizationMemberRequestContent {
    /** List of user IDs to add to the organization as members. */
    members: string[];
    /** Accepts any additional properties */
    [key: string]: any;
}
