/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface CreatePhoneProviderSendTestRequestContent {
    /** The recipient phone number to receive a given notification. */
    to: string;
    delivery_method?: Management.PhoneProviderDeliveryMethodEnum;
}
