/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * SCIM Token
 */
export interface CreateScimTokenRequestContent {
    /** The scopes of the scim token */
    scopes?: string[];
    /** Lifetime of the token in seconds. Must be greater than 900 */
    token_lifetime?: number;
}
