/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface CreateVerifiableCredentialTemplateRequestContent {
    name: string;
    type: string;
    dialect: string;
    presentation: Management.MdlPresentationRequest;
    custom_certificate_authority?: string;
    well_known_trusted_issuers: string;
}
