/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

/**
 * Phone provider configuration schema
 */
export interface CreateBrandingPhoneProviderRequestContent {
    name: Management.PhoneProviderNameEnum;
    /** Whether the provider is enabled (false) or disabled (true). */
    disabled?: boolean;
    configuration?: Management.PhoneProviderConfiguration;
    credentials: Management.PhoneProviderCredentials;
    /** Accepts any additional properties */
    [key: string]: any;
}
