/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

/**
 * The payload for sending a test event to an event stream.
 */
export interface CreateEventStreamTestEventRequestContent {
    event_type: Management.EventStreamTestEventTypeEnum;
    data?: Management.TestEventDataContent;
}
