/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface CreatePhoneTemplateTestNotificationRequestContent {
    /** Destination of the testing phone notification */
    to: string;
    delivery_method?: Management.PhoneProviderDeliveryMethodEnum;
    /** Accepts any additional properties */
    [key: string]: any;
}
