/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface CreateCustomDomainRequestContent {
    /** Domain name. */
    domain: string;
    type: Management.CustomDomainProvisioningTypeEnum;
    verification_method?: Management.CustomDomainVerificationMethodEnum;
    tls_policy?: Management.CustomDomainTlsPolicyEnum;
    custom_client_ip_header?: Management.CustomDomainCustomClientIpHeader | undefined;
}
