/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface CreateUserPermissionsRequestContent {
    /** List of permissions to add to this user. */
    permissions: Management.PermissionRequestPayload[];
}
