/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface DeleteUserPermissionsRequestContent {
    /** List of permissions to remove from this user. */
    permissions: Management.PermissionRequestPayload[];
}
