/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteOrganizationMemberRolesRequestContent {
    /** List of roles IDs associated with the organization member to remove. */
    roles: string[];
}
