/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteOrganizationMembersRequestContent {
    /** List of user IDs to remove from the organization. */
    members: string[];
    /** Accepts any additional properties */
    [key: string]: any;
}
