/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteUserRolesRequestContent {
    /** List of roles IDs to remove from the user. */
    roles: string[];
}
