/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionHubspot =
    | Management.FlowActionHubspot.EnrollContact
    | Management.FlowActionHubspot.GetContact
    | Management.FlowActionHubspot.UpsertContact;

export namespace FlowActionHubspot {
    export interface EnrollContact extends Management.FlowActionHubspotEnrollContact {
        action: "ENROLL_CONTACT";
    }

    export interface GetContact extends Management.FlowActionHubspotGetContact {
        action: "GET_CONTACT";
    }

    export interface UpsertContact extends Management.FlowActionHubspotUpsertContact {
        action: "UPSERT_CONTACT";
    }
}
