/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionTwilio = Management.FlowActionTwilio.MakeCall | Management.FlowActionTwilio.SendSms;

export namespace FlowActionTwilio {
    export interface MakeCall extends Management.FlowActionTwilioMakeCall {
        action: "MAKE_CALL";
    }

    export interface SendSms extends Management.FlowActionTwilioSendSms {
        action: "SEND_SMS";
    }
}
