/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionActivecampaign =
    | Management.FlowActionActivecampaign.ListContacts
    | Management.FlowActionActivecampaign.UpsertContact;

export namespace FlowActionActivecampaign {
    export interface ListContacts extends Management.FlowActionActivecampaignListContacts {
        action: "LIST_CONTACTS";
    }

    export interface UpsertContact extends Management.FlowActionActivecampaignUpsertContact {
        action: "UPSERT_CONTACT";
    }
}
