/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionFlow =
    | Management.FlowActionFlow.BooleanCondition
    | Management.FlowActionFlow.DelayFlow
    | Management.FlowActionFlow.DoNothing
    | Management.FlowActionFlow.ErrorMessage
    | Management.FlowActionFlow.MapValue
    | Management.FlowActionFlow.ReturnJson
    | Management.FlowActionFlow.StoreVars;

export namespace FlowActionFlow {
    export interface BooleanCondition extends Management.FlowActionFlowBooleanCondition {
        action: "BOOLEAN_CONDITION";
    }

    export interface DelayFlow extends Management.FlowActionFlowDelayFlow {
        action: "DELAY_FLOW";
    }

    export interface DoNothing extends Management.FlowActionFlowDoNothing {
        action: "DO_NOTHING";
    }

    export interface ErrorMessage extends Management.FlowActionFlowErrorMessage {
        action: "ERROR_MESSAGE";
    }

    export interface MapValue extends Management.FlowActionFlowMapValue {
        action: "MAP_VALUE";
    }

    export interface ReturnJson extends Management.FlowActionFlowReturnJson {
        action: "RETURN_JSON";
    }

    export interface StoreVars extends Management.FlowActionFlowStoreVars {
        action: "STORE_VARS";
    }
}
