/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionOtp = Management.FlowActionOtp.GenerateCode | Management.FlowActionOtp.VerifyCode;

export namespace FlowActionOtp {
    export interface GenerateCode extends Management.FlowActionOtpGenerateCode {
        action: "GENERATE_CODE";
    }

    export interface VerifyCode extends Management.FlowActionOtpVerifyCode {
        action: "VERIFY_CODE";
    }
}
