/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionJwt =
    | Management.FlowActionJwt.DecodeJwt
    | Management.FlowActionJwt.SignJwt
    | Management.FlowActionJwt.VerifyJwt;

export namespace FlowActionJwt {
    export interface DecodeJwt extends Management.FlowActionJwtDecodeJwt {
        action: "DECODE_JWT";
    }

    export interface SignJwt extends Management.FlowActionJwtSignJwt {
        action: "SIGN_JWT";
    }

    export interface VerifyJwt extends Management.FlowActionJwtVerifyJwt {
        action: "VERIFY_JWT";
    }
}
