/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FlowActionJwtDecodeJwt {
    id: string;
    alias?: string;
    type: "JWT";
    allow_failure?: boolean;
    mask_output?: boolean;
    params: Management.FlowActionJwtDecodeJwtParams;
}
