/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionSalesforce =
    | Management.FlowActionSalesforce.CreateLead
    | Management.FlowActionSalesforce.GetLead
    | Management.FlowActionSalesforce.SearchLeads
    | Management.FlowActionSalesforce.UpdateLead;

export namespace FlowActionSalesforce {
    export interface CreateLead extends Management.FlowActionSalesforceCreateLead {
        action: "CREATE_LEAD";
    }

    export interface GetLead extends Management.FlowActionSalesforceGetLead {
        action: "GET_LEAD";
    }

    export interface SearchLeads extends Management.FlowActionSalesforceSearchLeads {
        action: "SEARCH_LEADS";
    }

    export interface UpdateLead extends Management.FlowActionSalesforceUpdateLead {
        action: "UPDATE_LEAD";
    }
}
