/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FlowActionStripeAddTaxId {
    id: string;
    alias?: string;
    type: "STRIPE";
    allow_failure?: boolean;
    mask_output?: boolean;
    params: Management.FlowActionStripeAddTaxIdParams;
}
