/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionXml = Management.FlowActionXml.ParseXml | Management.FlowActionXml.SerializeXml;

export namespace FlowActionXml {
    export interface ParseXml extends Management.FlowActionXmlParseXml {
        action: "PARSE_XML";
    }

    export interface SerializeXml extends Management.FlowActionXmlSerializeXml {
        action: "SERIALIZE_XML";
    }
}
