/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionAuth0 =
    | Management.FlowActionAuth0.CreateUser
    | Management.FlowActionAuth0.GetUser
    | Management.FlowActionAuth0.UpdateUser
    | Management.FlowActionAuth0.SendRequest;

export namespace FlowActionAuth0 {
    export interface CreateUser extends Management.FlowActionAuth0CreateUser {
        action: "CREATE_USER";
    }

    export interface GetUser extends Management.FlowActionAuth0GetUser {
        action: "GET_USER";
    }

    export interface UpdateUser extends Management.FlowActionAuth0UpdateUser {
        action: "UPDATE_USER";
    }

    export interface SendRequest extends Management.FlowActionAuth0SendRequest {
        action: "SEND_REQUEST";
    }
}
