/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionJson =
    | Management.FlowActionJson.CreateJson
    | Management.FlowActionJson.ParseJson
    | Management.FlowActionJson.SerializeJson;

export namespace FlowActionJson {
    export interface CreateJson extends Management.FlowActionJsonCreateJson {
        action: "CREATE_JSON";
    }

    export interface ParseJson extends Management.FlowActionJsonParseJson {
        action: "PARSE_JSON";
    }

    export interface SerializeJson extends Management.FlowActionJsonSerializeJson {
        action: "SERIALIZE_JSON";
    }
}
