/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FlowActionClearbitFindPerson {
    id: string;
    alias?: string;
    type: "CLEARBIT";
    allow_failure?: boolean;
    mask_output?: boolean;
    params: Management.FlowActionClearbitFindPersonParams;
}
