/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionStripe =
    | Management.FlowActionStripe.AddTaxId
    | Management.FlowActionStripe.CreateCustomer
    | Management.FlowActionStripe.CreatePortalSession
    | Management.FlowActionStripe.DeleteTaxId
    | Management.FlowActionStripe.FindCustomers
    | Management.FlowActionStripe.GetCustomer
    | Management.FlowActionStripe.UpdateCustomer;

export namespace FlowActionStripe {
    export interface AddTaxId extends Management.FlowActionStripeAddTaxId {
        action: "ADD_TAX_ID";
    }

    export interface CreateCustomer extends Management.FlowActionStripeCreateCustomer {
        action: "CREATE_CUSTOMER";
    }

    export interface CreatePortalSession extends Management.FlowActionStripeCreatePortalSession {
        action: "CREATE_PORTAL_SESSION";
    }

    export interface DeleteTaxId extends Management.FlowActionStripeDeleteTaxId {
        action: "DELETE_TAX_ID";
    }

    export interface FindCustomers extends Management.FlowActionStripeFindCustomers {
        action: "FIND_CUSTOMERS";
    }

    export interface GetCustomer extends Management.FlowActionStripeGetCustomer {
        action: "GET_CUSTOMER";
    }

    export interface UpdateCustomer extends Management.FlowActionStripeUpdateCustomer {
        action: "UPDATE_CUSTOMER";
    }
}
