/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionPipedrive =
    | Management.FlowActionPipedrive.AddDeal
    | Management.FlowActionPipedrive.AddOrganization
    | Management.FlowActionPipedrive.AddPerson;

export namespace FlowActionPipedrive {
    export interface AddDeal extends Management.FlowActionPipedriveAddDeal {
        action: "ADD_DEAL";
    }

    export interface AddOrganization extends Management.FlowActionPipedriveAddOrganization {
        action: "ADD_ORGANIZATION";
    }

    export interface AddPerson extends Management.FlowActionPipedriveAddPerson {
        action: "ADD_PERSON";
    }
}
