/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionClearbit = Management.FlowActionClearbit.FindPerson | Management.FlowActionClearbit.FindCompany;

export namespace FlowActionClearbit {
    export interface FindPerson extends Management.FlowActionClearbitFindPerson {
        action: "FIND_PERSON";
    }

    export interface FindCompany extends Management.FlowActionClearbitFindCompany {
        action: "FIND_COMPANY";
    }
}
