/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionAirtable =
    | Management.FlowActionAirtable.CreateRecord
    | Management.FlowActionAirtable.ListRecords
    | Management.FlowActionAirtable.UpdateRecord;

export namespace FlowActionAirtable {
    export interface CreateRecord extends Management.FlowActionAirtableCreateRecord {
        action: "CREATE_RECORD";
    }

    export interface ListRecords extends Management.FlowActionAirtableListRecords {
        action: "LIST_RECORDS";
    }

    export interface UpdateRecord extends Management.FlowActionAirtableUpdateRecord {
        action: "UPDATE_RECORD";
    }
}
