/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FlowActionPipedriveAddDeal {
    id: string;
    alias?: string;
    type: "PIPEDRIVE";
    allow_failure?: boolean;
    mask_output?: boolean;
    params: Management.FlowActionPipedriveAddDealParams;
}
