/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FormBlockHtml {
    id: string;
    category: Management.FormComponentCategoryBlockConst;
    config?: Management.FormBlockHtmlConfig;
}
