/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FormFieldDropdown {
    id: string;
    category: Management.FormComponentCategoryFieldConst;
    config?: Management.FormFieldDropdownConfig;
    label?: string;
    hint?: string;
    required?: boolean;
    sensitive?: boolean;
}
