/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FormField =
    | Management.FormField.Boolean
    | Management.FormField.Cards
    | Management.FormField.Choice
    | Management.FormField.Custom
    | Management.FormField.Date_
    | Management.FormField.Dropdown
    | Management.FormField.Email
    | Management.FormField.File_
    | Management.FormField.Legal
    | Management.FormField.Number
    | Management.FormField.Password
    | Management.FormField.Payment
    | Management.FormField.Social
    | Management.FormField.Tel
    | Management.FormField.Text
    | Management.FormField.Url;

export namespace FormField {
    export interface Boolean extends Management.FormFieldBoolean {
        type: "BOOLEAN";
    }

    export interface Cards extends Management.FormFieldCards {
        type: "CARDS";
    }

    export interface Choice extends Management.FormFieldChoice {
        type: "CHOICE";
    }

    export interface Custom extends Management.FormFieldCustom {
        type: "CUSTOM";
    }

    export interface Date_ extends Management.FormFieldDate {
        type: "DATE";
    }

    export interface Dropdown extends Management.FormFieldDropdown {
        type: "DROPDOWN";
    }

    export interface Email extends Management.FormFieldEmail {
        type: "EMAIL";
    }

    export interface File_ extends Management.FormFieldFile {
        type: "FILE";
    }

    export interface Legal extends Management.FormFieldLegal {
        type: "LEGAL";
    }

    export interface Number extends Management.FormFieldNumber {
        type: "NUMBER";
    }

    export interface Password extends Management.FormFieldPassword {
        type: "PASSWORD";
    }

    export interface Payment extends Management.FormFieldPayment {
        type: "PAYMENT";
    }

    export interface Social extends Management.FormFieldSocial {
        type: "SOCIAL";
    }

    export interface Tel extends Management.FormFieldTel {
        type: "TEL";
    }

    export interface Text extends Management.FormFieldText {
        type: "TEXT";
    }

    export interface Url extends Management.FormFieldUrl {
        type: "URL";
    }
}
