/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FormFieldPayment {
    id: string;
    category: Management.FormComponentCategoryFieldConst;
    config: Management.FormFieldPaymentConfig;
    label?: string;
    hint?: string;
    required?: boolean;
    sensitive?: boolean;
}
