/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FormBlock =
    | Management.FormBlock.Divider
    | Management.FormBlock.Html
    | Management.FormBlock.Image
    | Management.FormBlock.JumpButton
    | Management.FormBlock.ResendButton
    | Management.FormBlock.NextButton
    | Management.FormBlock.PreviousButton
    | Management.FormBlock.RichText;

export namespace FormBlock {
    export interface Divider extends Management.FormBlockDivider {
        type: "DIVIDER";
    }

    export interface Html extends Management.FormBlockHtml {
        type: "HTML";
    }

    export interface Image extends Management.FormBlockImage {
        type: "IMAGE";
    }

    export interface JumpButton extends Management.FormBlockJumpButton {
        type: "JUMP_BUTTON";
    }

    export interface ResendButton extends Management.FormBlockResendButton {
        type: "RESEND_BUTTON";
    }

    export interface NextButton extends Management.FormBlockNextButton {
        type: "NEXT_BUTTON";
    }

    export interface PreviousButton extends Management.FormBlockPreviousButton {
        type: "PREVIOUS_BUTTON";
    }

    export interface RichText extends Management.FormBlockRichText {
        type: "RICH_TEXT";
    }
}
