/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FormNode = Management.FormNode.Flow | Management.FormNode.Router | Management.FormNode.Step;

export namespace FormNode {
    export interface Flow extends Management.FormFlow {
        type: "FLOW";
    }

    export interface Router extends Management.FormRouter {
        type: "ROUTER";
    }

    export interface Step extends Management.FormStep {
        type: "STEP";
    }
}
