/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FormFieldPaymentConfigCharge =
    | Management.FormFieldPaymentConfigCharge.OneOff
    | Management.FormFieldPaymentConfigCharge.Subscription;

export namespace FormFieldPaymentConfigCharge {
    export interface OneOff extends Management.FormFieldPaymentConfigChargeOneOff {
        type: "ONE_OFF";
    }

    export interface Subscription {
        type: "SUBSCRIPTION";
        subscription: Management.FormFieldPaymentConfigSubscription;
    }
}
