/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FormWidget =
    | Management.FormWidget.Auth0VerifiableCredentials
    | Management.FormWidget.GmapsAddress
    | Management.FormWidget.Recaptcha;

export namespace FormWidget {
    export interface Auth0VerifiableCredentials extends Management.FormWidgetAuth0VerifiableCredentials {
        type: "AUTH0_VERIFIABLE_CREDENTIALS";
    }

    export interface GmapsAddress extends Management.FormWidgetGMapsAddress {
        type: "GMAPS_ADDRESS";
    }

    export interface Recaptcha extends Management.FormWidgetRecaptcha {
        type: "RECAPTCHA";
    }
}
