/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FormWidgetAuth0VerifiableCredentials {
    id: string;
    category: Management.FormComponentCategoryWidgetConst;
    config: Management.FormWidgetAuth0VerifiableCredentialsConfig;
    label?: string;
    hint?: string;
    required?: boolean;
    sensitive?: boolean;
}
