/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ImportEncryptionKeyRequestContent {
    /** Base64 encoded ciphertext of key material wrapped by public wrapping key. */
    wrapped_key: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
