/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Access level for the organization (e.g., "none", "full").
 */
export type OrganizationAccessLevelEnum = "none" | "readonly" | "limited" | "full";
export const OrganizationAccessLevelEnum = {
    None: "none",
    Readonly: "readonly",
    Limited: "limited",
    Full: "full",
} as const;
