/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateRoleRequestContent {
    /** Name of this role. */
    name?: string;
    /** Description of this role. */
    description?: string;
}
