/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

/**
 * Branding theme
 */
export interface UpdateBrandingThemeRequestContent {
    borders: Management.BrandingThemeBorders;
    colors: Management.BrandingThemeColors;
    /** Display Name */
    displayName?: string;
    fonts: Management.BrandingThemeFonts;
    page_background: Management.BrandingThemePageBackground;
    widget: Management.BrandingThemeWidget;
}
